### ISSUE TITLE
Attacks only date tool?

### ISSUE THREAD

**Issue by rugk** [hannob/httpstime#1]
> In theory the server could try to attack the parser in the "date" tool.

Well… it could also attack grep, or bash. The data is passed to them, too.

**Comment by hannob** [comment]
I don't see that as very plausable. If you want it changed propose a concrete wording or open a pull req.

**Comment by rugk** [comment]
Yeah, of course that's theoretical. But you also say the date attack is theoretical… so what makes `grep` or `bash` more robust against attacks than `date`? I see no real reason for it… (I would like to hear explanations if that is really the case, though.) I just also see no "plausible" attack on date…

So either the `date` comment is superfluous, or you may also add `grep` (which AFAIK is a much more complex program with a complex syntax than a single program) and `bash` (thinking of shellshock and [the parsing in these lines](https://github.com/hannob/httpstime/blob/master/httpstime#L19-L20) here).

**Comment by hannob** [comment]
well, date is parsing the string, which is the classic way where all the usual memory corruption things happen. That I found no bugs in date was a surprise to me. It's also more or less unusual to pass an untrusted string to date.

The use of grep just looks for one string matching another. While not completely impossible, it seems hard to imagine how you can mess that up without noticing in a tool as widely used as grep.
Bash just takes the string into a variable and does a string replace.

So neither bash nor grep try to understand the format within any of the untrusted strings they handle.

**Comment by rugk** [comment]
For bash in your script you use RegExp (You use `^`.), so it is harder than just a "search and replace".

But the rest makes sense. Thanks for your explanation.
